export const tables=['leads','clients','projects','quotes','invoices','payments','renewals','expenses','documents','settings'];
export const statuses={leads:['New','Contacted','Demo Sent','Interested','Quote Sent','Negotiating','Won','Lost'],projects:['Lead','Planning','Design','Development','Review','Waiting for Client','Completed','Maintenance','Cancelled'],quotes:['Draft','Sent','Accepted','Rejected','Expired'],invoices:['Draft','Sent','Partially Paid','Paid','Overdue','Void']};
export const schemas={
 leads:{name:'text',businessName:'text',email:'email',phone:'tel',whatsapp:'tel',source:'text',projectType:'text',estimatedBudget:'number',status:'status',notes:'textarea',nextFollowUp:'date'},
 clients:{clientName:'text',businessName:'text',email:'email',phone:'tel',whatsapp:'tel',address:'text',city:'text',country:'text',notes:'textarea'},
 projects:{clientId:'client',name:'text',type:'text',description:'textarea',status:'status',startDate:'date',deadline:'date',completionDate:'date',quotedAmount:'number',finalAmount:'number',currency:'currency',notes:'textarea',links:'textarea'},
 quotes:{number:'text',clientId:'client',projectId:'project',issueDate:'date',expiryDate:'date',currency:'currency',lineItems:'items',discount:'number',tax:'number',terms:'textarea',notes:'textarea',status:'status'},
 invoices:{number:'text',clientId:'client',projectId:'project',issueDate:'date',dueDate:'date',currency:'currency',lineItems:'items',discount:'number',tax:'number',terms:'textarea',notes:'textarea',paymentDetails:'textarea',status:'status'},
 payments:{invoiceId:'invoice',clientId:'client',projectId:'project',amount:'number',currency:'currency',date:'date',method:'text',reference:'text',notes:'textarea'},
 renewals:{clientId:'client',projectId:'project',type:'text',name:'text',provider:'text',accountReference:'text',purchaseDate:'date',expiryDate:'date',cost:'number',clientCharge:'number',currency:'currency',autoRenew:'checkbox',status:'text',url:'url',notes:'textarea',customIntervals:'text'},
 expenses:{date:'date',clientId:'client',projectId:'project',category:'text',description:'text',amount:'number',currency:'currency',provider:'text',notes:'textarea'},
 documents:{clientId:'client',projectId:'project',type:'text',name:'text',url:'url',notes:'textarea'},
 settings:{businessName:'text',ownerName:'text',email:'email',phone:'tel',whatsapp:'tel',address:'textarea',website:'url',defaultCurrency:'currency',invoicePrefix:'text',invoiceStart:'number',paymentDetails:'textarea',defaultTerms:'textarea',defaultDueDays:'number',reminderIntervals:'text',appearance:'text'}
};
export const round=n=>Math.round((Number(n)+Number.EPSILON)*100)/100;
export function totals(doc){const subtotal=round((doc.lineItems||[]).reduce((s,x)=>s+Number(x.quantity||0)*Number(x.rate||0),0));const discount=round(Number(doc.discount||0));const tax=round((subtotal-discount)*Number(doc.tax||0)/100);return {subtotal,discount,tax,total:round(Math.max(0,subtotal-discount+tax))}}
export function balance(invoice,payments){const paid=round(payments.filter(p=>p.invoiceId===invoice.id).reduce((s,p)=>s+Number(p.amount||0),0));const total=totals(invoice).total;return {paid,balance:round(Math.max(0,total-paid)),status:invoice.status==='Void'?'Void':paid>=total&&total>0?'Paid':paid>0?'Partially Paid':invoice.status==='Draft'?'Draft':invoice.dueDate&&invoice.dueDate<new Date().toISOString().slice(0,10)?'Overdue':'Sent'}}
export function convertQuote(q,number){if(q.status!=='Accepted')throw Error('Accept the quote before converting it.');return {number,clientId:q.clientId,projectId:q.projectId,issueDate:new Date().toISOString().slice(0,10),dueDate:'',currency:q.currency,lineItems:q.lineItems.map(x=>({...x})),discount:q.discount,tax:q.tax,terms:q.terms,notes:q.notes,status:'Draft',sourceQuoteId:q.id}}
export const dayDiff=(date,now=new Date())=>Math.ceil((new Date(`${date}T12:00:00Z`)-new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate(),12)))/86400000);
export function expiryCategory(date,now=new Date()){const d=dayDiff(date,now);return d<0?'Expired':d<=7?'Due within 7 days':d<=30?'Due within 30 days':d<=90?'Due within 90 days':'Later'}
export function reminderEvents(record,now=new Date()){if(!record.expiryDate)return [];const days=[90,30,7,0,...String(record.customIntervals||'').split(',').map(Number).filter(x=>Number.isInteger(x)&&x>0&&x<=365&&x<=365)];const diff=dayDiff(record.expiryDate,now);return [...new Set(days)].filter(d=>diff===d).map(d=>({id:`${record.id}:${record.expiryDate}:${d}`,recordId:record.id,daysBefore:d,category:expiryCategory(record.expiryDate,now)}))}
export function profit(project, payments, expenses){const revenue=round(payments.filter(p=>p.projectId===project.id&&p.currency===project.currency).reduce((s,p)=>s+Number(p.amount),0));const cost=round(expenses.filter(e=>e.projectId===project.id&&e.currency===project.currency).reduce((s,e)=>s+Number(e.amount),0));return {currency:project.currency,revenue,cost,estimatedProfit:round(revenue-cost)}}
export function leadToClient(lead){return {clientName:lead.name,businessName:lead.businessName,email:lead.email,phone:lead.phone,whatsapp:lead.whatsapp,notes:lead.notes,sourceLeadId:lead.id}}
export function validateBackup(data){if(!data||data.format!=='anza-local-v1'||data.version!==1||!data.records||typeof data.records!=='object'||!Number.isFinite(Date.parse(data.createdAt)))throw Error('Unsupported or invalid backup.');for(const t of tables){if(!Array.isArray(data.records[t]))throw Error(`Missing table ${t}.`);const ids=new Set();for(const row of data.records[t]){if(!row||typeof row.id!=='string'||!row.id||ids.has(row.id))throw Error(`Invalid or duplicate record in ${t}.`);ids.add(row.id)}}return data}
export const serializeBackup=records=>JSON.stringify({format:'anza-local-v1',version:1,createdAt:new Date().toISOString(),records});
