import test from 'node:test';
import assert from 'node:assert/strict';
import {totals,balance,convertQuote,expiryCategory,reminderEvents,profit,leadToClient,serializeBackup,validateBackup,tables} from '../admin/src/domain.mjs';
const invoice={id:'i',lineItems:[{quantity:2,rate:100},{quantity:1,rate:25}],discount:25,tax:10,status:'Sent',dueDate:'2026-10-10'};
test('invoice totals, payments and balance',()=>{assert.deepEqual(totals(invoice),{subtotal:225,discount:25,tax:20,total:220});assert.deepEqual(balance(invoice,[{invoiceId:'i',amount:100}]),{paid:100,balance:120,status:'Partially Paid'});assert.equal(balance(invoice,[{invoiceId:'i',amount:220}]).status,'Paid')});
test('accepted quote converts without sharing line item objects',()=>{const q={id:'q',status:'Accepted',lineItems:[{description:'Build',quantity:1,rate:200}],currency:'LKR'};const i=convertQuote(q,'ANZA-2026-0001');i.lineItems[0].rate=300;assert.equal(q.lineItems[0].rate,200);assert.equal(i.sourceQuoteId,'q');assert.throws(()=>convertQuote({...q,status:'Draft'},'x'))});
test('renewal categories and exact reminder milestones',()=>{const now=new Date('2026-09-29T12:00:00Z');assert.equal(expiryCategory('2026-09-28',now),'Expired');assert.equal(expiryCategory('2026-10-06',now),'Due within 7 days');assert.equal(expiryCategory('2026-10-20',now),'Due within 30 days');assert.equal(reminderEvents({id:'r',expiryDate:'2026-10-06'},now)[0].daysBefore,7);assert.equal(reminderEvents({id:'r',expiryDate:'2026-10-05'},now).length,0)});
test('profit is currency aware and lead conversion keeps provenance',()=>{assert.deepEqual(profit({id:'p',currency:'LKR'},[{projectId:'p',currency:'LKR',amount:100},{projectId:'p',currency:'USD',amount:50}],[{projectId:'p',currency:'LKR',amount:30}]),{currency:'LKR',revenue:100,cost:30,estimatedProfit:70});assert.equal(leadToClient({id:'l',name:'A'}).sourceLeadId,'l')});
test('backup round-trip and structural validation',()=>{const records=Object.fromEntries(tables.map(t=>[t,[]]));records.clients.push({id:'c',clientName:'A'});const backup=validateBackup(JSON.parse(serializeBackup(records)));assert.equal(backup.records.clients[0].id,'c');assert.throws(()=>validateBackup({...backup,records:{...records,clients:[{id:'c'},{id:'c'}]}}))});
