from pathlib import Path
from html import escape
import json
root=Path(__file__).parent
media=json.loads((root/'media.json').read_text())
projects=[
('northline-hotel','Northline Hotel','Hospitality website','An editorial booking experience for an independent hotel.','A hospitality concept focused on clear room discovery and a direct enquiry path.','Present rooms, location, and the character of the property without burying practical details.','A restrained visual system, direct room comparison, and a prominent booking enquiry.',['Room detail pages','Availability enquiry','Local guide'],['Responsive design','Accessibility','Content architecture']),
('saffron-table','Saffron Table','Restaurant website','A menu-first digital home for a neighborhood restaurant.','A restaurant concept that puts the menu and reservations in easy reach.','Make hours, menu, and reservations obvious on mobile.','Clear information hierarchy with menu categories and a direct reservation action.',['Mobile menu','Hours and location','Reservation path'],['Responsive design','Semantic HTML','Performance']),
('form-and-found','Form & Found','E-commerce website','A quiet storefront concept for curated home goods.','A shop concept with considered product discovery and a simple checkout journey.','Help customers browse without visual clutter.','A product-led catalog with clear filters and product details.',['Product filters','Product detail','Cart flow'],['UI design','Commerce architecture','Accessibility']),
('counterpoint-pos','Counterpoint POS','POS / admin system','A focused operating surface for daily sales and inventory.','A point-of-sale concept for small business workflows.','Keep common actions fast while preserving clear records.','Task-oriented layouts for transactions, stock, and reporting.',['Sales overview','Inventory tracking','Daily close'],['Product design','Data modeling','Offline planning']),
('atlas-desk','Atlas Desk','Web application','A practical dashboard concept for coordinating project work.','A web application concept for tracking work across a growing team.','Make project status and next actions visible.','A modular workspace with concise status and activity views.',['Project boards','Activity log','Permissions model'],['Web application','UX systems','Data architecture'])]
services=[('Website Design & Development','A complete site shaped around your business goals.','Growing businesses','Strategy, design, development, launch'),('Business Websites','A clear digital presence that helps visitors trust and contact you.','Local and service businesses','Service pages, contact paths, SEO foundations'),('Hotel & Hospitality Websites','A welcoming property experience with useful booking journeys.','Hotels and stays','Rooms, amenities, location, enquiry'),('Restaurant Websites','Menus and reservations designed for real customers on the move.','Restaurants and cafés','Menu, hours, location, reservations'),('E-commerce / Shop Websites','Storefronts that make browsing and buying straightforward.','Retail brands','Catalog, product pages, checkout planning'),('Admin Dashboards','Working surfaces that turn business records into decisions.','Operations teams','Reporting, roles, workflows'),('POS / Business Software','Tools that support transactions and everyday operations.','Shops and service teams','Sales, inventory, reporting'),('Web Applications','Custom software built around the task at hand.','Teams with specific workflows','Product architecture, interfaces, integrations'),('AI-enabled Tools','Focused automations with appropriate human oversight.','Teams with repetitive work','Workflow review, integration, safeguards'),('Maintenance & Support','Ongoing improvements, fixes and technical care.','Existing site owners','Updates, monitoring, enhancements')]
